FullStack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('api/', include('question_list.api_urls')),
    path('', include('question_list.urls'))

]

accounts/urls.py
from django.urls import path
from .views import SignUpView, ProfileView

app_name = 'account'
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

question_list/urls.py
from django.urls import path
from .views import QuestionGroupView, QuestionListCreateView
from django.views.generic import TemplateView

app_name = 'question_list'
urlpatterns = [
    path("<int:pk>/", TemplateView.as_view(template_name='question_list.html'), name="react"),
    path("create_new/", QuestionListCreateView.as_view(), name="new group"),
    path("", QuestionGroupView.as_view(), name="home"),

]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

question_list/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser


class QuestionList(models.Model):
    title = models.CharField(max_length=300)
    description = models.CharField(max_length=1500)
    creation_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title


class Question(models.Model):
    text = models.CharField(max_length=1000)
    answer = models.DecimalField(decimal_places=3, max_digits=13)
    question_group = models.ForeignKey(QuestionList, related_name='question_rel', on_delete=models.CASCADE)
    position = models.IntegerField()
    visible = models.IntegerField()

    def __str__(self):
        return self.text

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
        )

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from question_list.models import QuestionList
from .forms import CustomUserCreationForm
from django.views.generic import ListView


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"


class ProfileView(ListView):
    model = QuestionList
    template_name = 'profiles.html'

    def get_queryset(self):
        return QuestionList.objects.filter(author=self.request.user)

question_list/views.py
from django.views.generic import ListView
from .models import QuestionList
from rest_framework import viewsets, generics
from .serializers import QuestionListSerializer
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

class QuestionGroupView(ListView):
    model = QuestionList
    template_name = 'index.html'


class ListQuestionList(generics.ListAPIView):
    serializer_class = QuestionListSerializer
    queryset = QuestionList.objects.all()


class DetailQuestionList(generics.RetrieveAPIView):
    serializer_class = QuestionListSerializer
    queryset = QuestionList.objects.all()


class QuestionListCreateView(LoginRequiredMixin, CreateView):
    model = QuestionList
    template_name = 'create_questions.html'
    fields = ['title', 'description' ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('profile')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Unnamed Full Stack Project{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<main>
    {% block content %}
    {% endblock content %}
</main>
</body>
</html>

templates/create_questions.html
{% extends "base.html" %}
{% block title %}Create Question Group{% endblock title %}
{% block content %}
    <h1>Create Question Group</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FullStack</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="grid-container">
    <img src="{% static 'images/Logo.svg' %}" alt="The logo" class="logo"/>
    <h1 class="title">
        Full Stack Project
    </h1>
    <div class="buttonPanel">
        {% if user.is_authenticated %}
            <div class="loginButtonContainer">
                <a href= "{% url 'logout' %}" class="loginButton">
                    Log out
                </a>
            </div>
            <div class="loginButtonContainer">
                <a href= "{% url 'account:profile' %}" class="loginButton">
                    See Profile
                </a>
            </div>
            {% if user.is_superuser %}
                <div class="loginButtonContainer">
                    <a href="{% url 'admin:index' %}" class="loginButton">
                        Admin
                    </a>
                </div>
            {% endif %}

            {% else %}
            <div class="loginButtonContainer">
                <a href="{% url 'login' %}" class="loginButton">
                    Log in
                </a>
            </div>
            <div class="loginButtonContainer">
                <a href="{% url 'account:signup' %}" class="loginButton">
                    Sign Up
                </a>
            </div>
        {% endif %}

    </div>
    {% for object in object_list %}
        <div class="card">
            <h2>
                {{ object.title }}
            </h2>
            <p>
                {{ object.description }}
            </p>
            <a href="{% url 'question_list:react' object.pk %}">
                Do this group
            </a>
        </div>
    {% empty %}
        <div class="centralPadding"></div>
        {% if user.is_authenticated %}
            <p>
                Nothing here yet. Why not make your own?
            </p>
        {% else %}
            <p>
                Nothing here yet. Log in and make your own!
            </p>
        {% endif %}
    {% endfor %}
</div>
</body>
</html>

templates/profiles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FullStack</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="grid-container">
    <img src="{% static 'images/Logo.svg' %}" alt="The logo" class="logo"/>
    <h1 class="title">
        {{user.username}}'s Profile 
    </h1>
    <div class="buttonPanel">
        <div class="loginButtonContainer">
            <a href= "{% url 'logout' %}" class="loginButton">
                Log out
            </a>
        </div>
        <div class="loginButtonContainer">
            <a href= "{% url 'question_list:home' %}" class="loginButton">
                See Home
            </a>
        </div>
        <div class="loginButtonContainer">
            <a href= "{% url 'question_list:new group' %}" class="loginButton">
                Create Question
            </a>
        </div>
        {% if user.is_superuser %}
        <div class="loginButtonContainer">
            <a href="{% url 'admin:index' %}" class="loginButton">
                Admin
            </a>
        </div>
        {% endif %}

    </div>
    {% for object in object_list %}
        <div class="card">
            <h2>
                {{ object.title }}
            </h2>
            <p>
                {{ object.description }}
            </p>
            <a href="{% url 'question_list:react' object.pk %}">
                Do this group
            </a>
            <a href="{% url 'question_list:react' object.pk %}">
                Edit Questions 
            </a>
        </div>
    {% empty %}
        <div class="centralPadding"></div>
        <p class="centralMessage">
            Nothing here yet. Why not make your own?
        </p>
    {% endfor %}
</div>
</body>
</html>

templates/question_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="theme-color" content="#000000"/>
    <meta
            name="description"
            content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png"/>
    <!--
      manifest.json provides metadata used when your web app is installed on a
      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    -->
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json"/>
    <!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
    <title>Unnammed React App</title>
</head>
<body>
<noscript>You need to enable JavaScript to run this app.</noscript>
<div id="root"></div>
<script type='module' src="{% static 'index-bundle.js' %}"></script>
<!--
  This HTML file is a template.
  If you open it directly in the browser, you will see an empty page.

  You can add webfonts, meta tags, or analytics to this file.
  The build step will place the bundled scripts into the <body> tag.

  To begin the development, run `npm start` or `yarn start`.
  To create a production bundle, use `npm run build` or `yarn build`.
-->
</body>
</html>